name: CI Workflow

# Trigger the workflow on push to the default branch
on:
  push:
    branches:
      - dev

# Define the jobs
jobs:
  build-and-test:
    # Specify the environment where the job runs
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test
